[project]
name = "deepfloorplan"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "gradio>=3.36.1",
    "inference>=0.49.5",
    "supervision>=0.25.1",
    "tensorflow>=2.19.0",
]
